### ISSUE TITLE
problem on line 20 in index.php and no login shortcut

### ISSUE THREAD

**Issue by sltgc2** [josephernest/bloggggg#4]
Hi !

I encountered 2 problems :
1) I've just put the folder on my web server and then since the first launch on my website this sentence appears : "Notice : only variables should be passed by reference on [...] index.php on line 20".
2) There's no login shortcut on the footer on my bloggggg's home page.

Last question : Is your version 1.0 embed online editor as it's written in READ.me on github and in your demo ?
I'm totally a newbie and I didn't make any modification within your folder. I don't understand. Can you help me please ?
Thx

**Comment by the-ft** [comment]
@sltgc2 
your problem has todo with your web server and maybe php version.

when i tested it and got into problems too. 
mine had todo with the file ".htaccess" (_it holds instructions for the Apache web server to for example overwrite the URL (in the addressbar), so that you dont see like "index.php?/?tag-news" but instead a nicer "tag/news"._)
i m running NGINX as a web server. for NGINX there are some "Apache .htaccess to NGINX converter" out there.
so check what server (and php) you are running!

btw. your error message points towards php -> [stackoverflow](https://stackoverflow.com/questions/4636166/only-variables-should-be-passed-by-reference) and [line 53](https://github.com/josephernest/bloggggg/blob/f3bd5fc573264b110fe60492b9c8cc6387e0f52e/index.php#L53)

**Comment by sltgc2** [comment]
@the-ft 

Thanks for your answer.
I think you're right : I tried on an another web server and it's OK.
Btw, thanks for your last advice.
